--TASK1
CREATE DATABASE COMPANY

USE COMPANY
--TASK2
CREATE TABLE EMPLOYEES(
ID INT PRIMARY KEY,
NAME VARCHAR(50),
SALARY DECIMAL
)
--TASK3
INSERT INTO EMPLOYEES
	VALUES(10, 'AHMED', 3000),(11, 'ALI', 4000)
--TASK4
UPDATE EMPLOYEES
	SET SALARY = 3500
	WHERE ID = 10
--TASK5
ALTER TABLE EMPLOYEES 
	ADD DEPARTMENT INT
--TASK6
ALTER TABLE EMPLOYEES 
	ALTER COLUMN DEPARTMENT INT NOT NULL
--TASK7
CREATE TABLE DEPARTMENTS(
	DEPARTMENTID INT PRIMARY KEY,
	DEPARTMENTNAME VARCHAR(30)
)
--TASK8
ALTER TABLE EMPLOYEES
	ADD FOREIGN KEY (DEPARTMENT) REFERENCES DEPARTMENTS(DEPARTMENTID)
--TASK9
SELECT *
	FROM EMPLOYEES
--TASK10
SELECT *
	FROM EMPLOYEES
	WHERE SALARY > 3500
--TASK11
INSERT INTO DEPARTMENTS
	VALUES(100, 'CS'),(200, 'IT')
UPDATE EMPLOYEES
	SET DEPARTMENT = 200
	WHERE ID = 10

--ADDITIONAL
INSERT INTO EMPLOYEES
	VALUES(12, 'ANAS', 12000, 200), (13, 'HISHAM', 22000, 100)

SELECT *
	FROM EMPLOYEES

UPDATE EMPLOYEES
	SET DEPARTMENT = 100
	WHERE NAME = 'ALI'

INSERT INTO DEPARTMENTS
	VALUES(300, 'AI'), (400,  'IS')

SELECT *
	FROM DEPARTMENTS


